# Generated by Django 2.0.1 on 2019-09-05 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.88, verbose_name='折扣价')),
            ],
            options={
                'verbose_name': '活动名称',
                'verbose_name_plural': '活动名称',
                'db_table': 'app_avtive_goods',
            },
        ),
        migrations.CreateModel(
            name='ActiveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='活动名称')),
                ('img1', models.ImageField(upload_to='actives', verbose_name='活动图片')),
                ('start_time', models.CharField(max_length=20, verbose_name='开始是时间')),
                ('end_time', models.CharField(max_length=20, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '活动信息',
                'verbose_name_plural': '活动信息',
                'db_table': 'app_active',
            },
        ),
        migrations.AddField(
            model_name='activegoodsmodel',
            name='active',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actives', to='actives.ActiveModel', verbose_name='活动名'),
        ),
        migrations.AddField(
            model_name='activegoodsmodel',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actives', to='goods.GoodsModel', verbose_name='商品名'),
        ),
    ]
