# Generated by Django 2.0.1 on 2019-09-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activegoodsmodel',
            options={'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
    ]
